language: c

sudo: false

compiler:
  - clang
  - gcc

env:
  global:
    - CC=$CC
    - LUAROCKS=2.3.0
    - CFLAGS=-Iinstall/lua/include
    - LDFLAGS=-Linstall/lua/lib
  matrix:
    - LUA=lua5.2
    - LUA=lua5.3

addons:
  apt:
    packages:
      - libtalloc-dev
      - libpcap-dev
      - libbsd-dev
      - liblua5.2
      - python-jinja2

cache: apt

before_install:
  - source .travis/setenv_lua.sh

script:
  - ./configure --with-debug || (cat config.log && false)
  - make
  - make install PREFIX=./dist
  - LD_LIBRARY_PATH=dist/lib make test
