language: c

sudo: false


env:
  global:
    - CC=$CC
    - LUAROCKS=2.3.0
    - CFLAGS=-Iinstall/lua/include
    - LDFLAGS=-Linstall/lua/lib
    - MAKE_TEST=1

matrix:
  include:
    - env: LUA=lua5.2
      os: linux
      compiler: gcc
    - env: LUA=lua5.2
      os: linux
      compiler: clang
    - env: LUA=lua5.3
      os: linux
      compiler: gcc
    - env: LUA=lua5.2 CROSS_COMPILE=i586-mingw32msvc- CC=i586-mingw32msvc-gcc CONFIGURE_ARGS="--platform=win32 --with-mingw=/usr/i586-mingw32msvc" MAKE_TEST=0
      os: linux
      compiler: gcc
    - env: LUA=lua5.2 OSX=10.10
      os: osx
      osx_image: xcode7.1
      compiler: clang
    - env: LUA=lua5.2 OSX=10.11
      os: osx
      osx_image: xcode7.2
      compiler: clang

addons:
  apt:
    packages:
      - libtalloc-dev
      - libpcap-dev
      - libbsd-dev
      - mingw32
      - python-jinja2

cache: apt

before_install:
  - test -z "$OSX" && source .travis/setenv_lua.sh
  - test -n "$OSX" && brew install python
  - test -n "$OSX" && pip install Jinja2

script:
  - ./configure --with-debug $CONFIGURE_ARGS || (cat config.log && false)
  - make
  - make install PREFIX=./dist
  - test $MAKE_TEST -eq 1 && LD_LIBRARY_PATH=dist/lib make test
