language: c

sudo: false


env:
  global:
    - CC=$CC
    - LUAROCKS=2.3.0
    - CFLAGS=-Iinstall/lua/include
    - LDFLAGS=-Linstall/lua/lib

matrix:
  include:
    - env: LUA=lua5.2
      os: linux
      compiler: gcc
    - env: LUA=lua5.2
      os: linux
      compiler: clang
    - env: LUA=lua5.3
      os: linux
      compiler: gcc
    - env: LUA=lua5.2 CROSS_COMPILE=i586-mingw32msvc-
      os: linux
      compiler: gcc
    - env: LUA=lua5.2 OSX=10.10
      os: osx
      osx_image: xcode7.1
      compiler: clang
    - env: LUA=lua5.2 OSX=10.11
      os: osx
      osx_image: xcode7.2
      compiler: clang

addons:
  apt:
    packages:
      - libtalloc-dev
      - libpcap-dev
      - libbsd-dev
      - mingw32
      - python-jinja2

cache: apt

before_install:
  - source .travis/setenv_lua.sh

script:
  - ./configure --with-debug || (cat config.log && false)
  - make
  - make install PREFIX=./dist
  - LD_LIBRARY_PATH=dist/lib make test
