language: c

sudo: false

env:
  global:
    - CC=$CC
    - CROSS_COMPILE=""
    - CONFIGURE_ARGS=""
    - CFLAGS=-Iinstall/lua/include
    - LDFLAGS=-Linstall/lua/lib
    - MAKE_TEST=1
    - LUA=x
    - LUAROCKS=2.3.0
    - OSX=x

matrix:
  include:
    - env: LUA=lua5.2
      os: linux
      compiler: gcc
    - env: LUA=lua5.2
      os: linux
      compiler: clang
    - env: LUA=lua5.3
      os: linux
      compiler: gcc
    - env: LUA= CROSS_COMPILE=i586-mingw32msvc- CC=i586-mingw32msvc-gcc CONFIGURE_ARGS="--platform=win32 --with-mingw=/usr/i586-mingw32msvc" MAKE_TEST=0
      os: linux
      compiler: gcc
    - env: LUA=x OSX=10.10
      os: osx
      osx_image: xcode7.1
      compiler: clang
    - env: LUA=x OSX=10.11
      os: osx
      osx_image: xcode7.2
      compiler: clang

addons:
  apt:
    packages:
      - libtalloc-dev
      - libpcap-dev
      - libbsd-dev
      - mingw32
      - mingw32-runtime
      - python-jinja2
      - wine

cache: apt

before_install:
  - echo "LUA=$LUA, OSX=$OSX"
  - if [ "$LUA" != "x" ]; then source .travis/setenv_lua.sh; fi
  - if [ "$OSX" != "x" ]; then brew install lua libpcap python talloc portaudio; fi
  - if [ "$OSX" != "x" ]; then pip install --upgrade pip; fi
  - if [ "$OSX" != "x" ]; then pip install Jinja2; fi

script:
  - echo "CROSS_COMPILE=$CROSS_COMPILE, CC=$CC, CONFIGURE_ARGS=$CONFIGURE_ARGS"
  - CROSS_COMPILE="$CROSS_COMPILE" CC="$CROSS_COMPILE$CC" ./configure --with-debug $CONFIGURE_ARGS || (cat config.log && false)
  - make CROSS_COMPILE="$CROSS_COMPILE" CC="$CROSS_COMPILE$CC"
  - make CROSS_COMPILE="$CROSS_COMPILE" CC="$CROSS_COMPILE$CC" install PREFIX=./dist
  - if [ $MAKE_TEST -eq 1 ]; then LD_LIBRARY_PATH=dist/lib make test; fi
