language: c

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - libtalloc-dev
      - libpcap-dev
      - libbsd-dev
      - python-jinja2

cache: apt

script:
  - export CC=$CC
  - ./configure --with-debug || (cat config.log && false)
  - make
  - make install PREFIX=./dist
  - LD_LIBRARY_PATH=dist/lib make test
