language: c

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - libtalloc-dev
      - libpcap-dev
      - portaudio-dev

cache: apt

script: scons --with-debug || (cat config.log && false)
