language: c

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - libtalloc-dev
      - libpcap-dev
      - libbsd-dev
      - python-jinja2

cache: apt

script:
  - export CC=$CC
  - ./configure && make && make test || (cat config.log && false)
