import os
import sys

Import('env')

localenv = env.Clone()
localenv.Append(
    LIBS=[
        env['libdmrfec_name'],
        env['libdmr_name'],
        'mbe',
        'portaudio',
    ],
    LIBPATH=[
        '#build/libdmr',
        '#build/libdmrfec',
        '#build/mbelib',
    ],
)

if sys.platform in ('linux2', 'darwin'):
    name = 'noisebridge'

if sys.platform == 'darwin':
    localenv.Append(
        CPPPATH=[
            '#support/darwin/portaudio/include',
        ],
        LIBPATH=[
            '#support/darwin/portaudio/lib',
        ],
        LINKFLAGS=[
            '-framework', 'CoreServices',
        ],
    )

if sys.platform == 'win32':
    name = 'noisebridge.exe'

noisebridge = localenv.Program(name, Glob('*.c'))
Return('noisebridge')
