import os
import sys

Import('env')

localenv = env.Clone()
localenv.Append(
    CPPPATH=[
        os.path.join('#src', 'dmr', 'support', 'tinycthread', 'source'),
    ],
    LIBS=[
        env['libdmrfec_name'],
        env['libdmr_name'],
        'SDL2',
    ],
    LIBPATH=[
        '#build/libdmr',
        '#build/libdmrfec',
    ],
)


if sys.platform in ('linux2', 'darwin'):
    name = 'noisebridge'

if sys.platform == 'darwin':
    localenv.Append(
        LINKFLAGS=[
            '-framework', 'CoreServices',
        ],
    )

if sys.platform == 'win32':
    name = 'noisebridge.exe'

noisebridge = localenv.Program(name, Glob('*.c'))
Return('noisebridge')
